
select * from customer limit 20;

--Q1. What is the total revenue generated by male vs female customers?
SELECT "Gender",
       SUM("Purchase Amount (USD)") AS revenue
FROM customer
GROUP BY "Gender";

--Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT "Customer ID", "Purchase Amount (USD)" from customer
where "Discount Applied" = 'Yes' and "Purchase Amount (USD)" >= (select avg("Purchase Amount (USD)") from customer)

--Q3. Which are the top 5 products with the highest average review rating?
SELECT "Item Purchased", ROUND(AVG("Review Rating":: numeric),2) as "Average Product Rating"
FROM Customer
GROUP BY "Item Purchased"
ORDER BY AVG("Review Rating") desc
limit 5;

--Q4. Compare the average purchase amounts between standard and express shipping.
select "Shipping Type", Round(avg("Purchase Amount (USD)":: numeric), 2)
from customer 
where "Shipping Type" in ('Standard', 'Express')
GROUP BY "Shipping Type"

--Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select "Subscription Status",
count ("Customer ID") as "Total Customers",
round(avg("Purchase Amount (USD)":: numeric), 2) as "Avg Spend",
round(sum("Purchase Amount (USD)":: numeric), 2) as "Total Revenue"
from customer
group by "Subscription Status"
order by "Total Revenue", "Avg Spend"

--Q6. Which 5 products have the highest percentage of purchase with discounts applied?
SELECT "Item Purchased",
ROUND(100*SUM(
	CASE 
		WHEN "Discount Applied" = 'Yes' 
		THEN 1 
		ELSE 0
		END)/COUNT(*),2) as "Discount Rate"
	FROM Customer
	GROUP BY "Item Purchased"
	ORDER BY "Discount Rate" desc
	limit 5;

--Q7. Segement customers into New, returning, and loyal based on their total number of previous purchases, and show the count of each segment.
with customer_type as (
SELECT customer_id, previous_purchases,
CASE 
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM customer)

select customer_segment,count(*) AS "Number of Customers" 
from customer_type 
group by customer_segment;

--Q8. What are the top 3 most purchased products within each category? 
WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;
 
--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

--Q10. What is the revenue contribution of each age group? 
SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue desc;
